### ISSUE TITLE
"SmartSelect is not a function" error running SmartReconnectTracks

### ISSUE THREAD

**Issue by daxliniere** [duritskiy/easyeda-MyExtensions#4]
I have a bunch of tracks that have become dissociated with the components they connect. Rather than having to manually type the correct net value or (worse still) delete+recreate them, I was hoping to use this script to correct the connections.

![image](https://user-images.githubusercontent.com/8109020/229323608-0c0b5209-0554-4d91-ac72-0aa35fb949bf.png)

However, when I run it, I get this error:

**Error: TypeError:ms.SmartSelect is not a function TypeError: ms.SmartSelect is not a function at SmartReconnectTracks (eval at <anonymous> (eval at <anonymous> (https://easyeda.com/editor/6.5.22/js/main.min.js:1:1)), <anonymous>:193:4) at _userjs_859321_ (eval at <anonymous> (eval at <anonymous> (https://easyeda.com/editor/6.5.22/js/main.min.js:1:1)), <anonymous>:31:1) at eval (eval at <anonymous> (https://easyeda.com/editor/6.5.22/js/main.min.js:1:1)), <anonymous>:807:45)**

Is this user error or is it not designed for this task?

Thanks in advance,
Dax.

**Comment by duritskiy** [comment]
I think it is user error.
Give me your scheme and pcb for example, and I create example video for you

**Comment by daxliniere** [comment]
Thank you @duritskiy. Is it possible to run 4SmartReconnectTracks without running the first 3 actions?

Alternatively, do you have (or could you create) a script that would solve the above problem of traces becoming dissociated with the pins that intersect them?

**Comment by duritskiy** [comment]
I tried, but nothing worked. Without changing the name of networks in SCH, it is not possible to change the names of networks in PCB

**Comment by duritskiy** [comment]
4SmartReconnectTracks can run on its own, but you need to run 1SmartCopy once the first time. This is necessary for the "SmartSelect()" function to be loaded.
This means that in EasyEda it is desirable to install all four scripts such as
1SmartCopy.js
SmartPaste.js
SmartRenamePref.js
SmartReconnectTracks.js

**Comment by daxliniere** [comment]
Hey @duritskiy! I got it to work! Thanks so much.

Perhaps an update to the scripts could contain a modification that when 1SmartCopy hasn't been run, SmartReconnectTracks will automatically populate its internal array to use the selected tracks/components? (And without having to specify a home point)

![EasyEDAScript_ReconnectWorking](https://user-images.githubusercontent.com/8109020/230786431-b8a3a38d-2f9b-437b-988d-1a4722426501.gif)

**Comment by duritskiy** [comment]
1SmartCopy needs to be pressed only once, this is necessary so that the error does not occur. Then you don't have to press it.
